[project]
name = "maisi"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "torch",
  "torchvision",
  "numpy",
  "tqdm",
  "wheel-stub",
  "simpleitk",
  "nibabel",
  "accelerate",
  "torchmetrics",
  "transformers[torch]",
  "monai[all]",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }